In [2]:
# Завдання 1
# Прочитайте csv файл (метод read_csv)
import pandas as pd

file_path = 'C:/Users/38099/Desktop/archive (1)/bestsellers with categories.csv'

data = pd.read_csv(file_path, encoding='cp1251')
print(data)

                                                  Name  \
0                        10-Day Green Smoothie Cleanse
1                                    11/22/63: A Novel
2              12 Rules for Life: An Antidote to Chaos
3                               1984 (Signet Classics)
4    5,000 Awesome Facts (About Everything!) (Natio...
..                                                 ...
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)
546  You Are a Badass: How to Stop Doubting Your Gr...
547  You Are a Badass: How to Stop Doubting Your Gr...
548  You Are a Badass: How to Stop Doubting Your Gr...
549  You Are a Badass: How to Stop Doubting Your Gr...

                       Author  User Rating  Reviews  Price  Year        Genre
0                    JJ Smith          4.7    17350      8  2016  Non Fiction
1                Stephen King          4.6     2052     22  2011      Fiction
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction
3               George Orwell          4.7    21424      6  2017      Fiction
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction
..                        ...          ...      ...    ...   ...          ...
545               Jeff Kinney          4.9     9413      8  2019      Fiction
546               Jen Sincero          4.7    14331      8  2016  Non Fiction
547               Jen Sincero          4.7    14331      8  2017  Non Fiction
548               Jen Sincero          4.7    14331      8  2018  Non Fiction
549               Jen Sincero          4.7    14331      8  2019  Non Fiction

[550 rows x 7 columns]

In [3]:
# Завдання 2
# Виведіть перші 10 рядків (метод head) 
data.head(10)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
5,A Dance with Dragons (A Song of Ice and Fire),George R. R. Martin,4.4,12643,11,2011,Fiction
6,A Game of Thrones / A Clash of Kings / A Storm...,George R. R. Martin,4.7,19735,30,2014,Fiction
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction
8,"A Higher Loyalty: Truth, Lies, and Leadership",James Comey,4.7,5983,3,2018,Non Fiction
9,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2016,Fiction

In [5]:
# Завдання 3
# Виведіть розміри датасету (метод shape) 
data.shape

(550, 7)

In [6]:
# Завдання 4
# Змініть назви всіх колонок: назва з маленької букви, без пробілів через підкреслення. 

data.columns = ['name', 'author', 'user_rating', 'reviews', 'price', 'year', 'genre']
data.head(10)

,name,author,user_rating,reviews,price,year,genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
5,A Dance with Dragons (A Song of Ice and Fire),George R. R. Martin,4.4,12643,11,2011,Fiction
6,A Game of Thrones / A Clash of Kings / A Storm...,George R. R. Martin,4.7,19735,30,2014,Fiction
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction
8,"A Higher Loyalty: Truth, Lies, and Leadership",James Comey,4.7,5983,3,2018,Non Fiction
9,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2016,Fiction

In [8]:
# Завдання 5
# Вивести кількість пропусків у кожному стовпчику
missing_values = data.isna().sum()

print("Кількість пропусків у кожному стовпці:")
print(missing_values)

Кількість пропусків у кожному стовпці:
name           0
author         0
user_rating    0
reviews        0
price          0
year           0
genre          0
dtype: int64

In [9]:
# Завдання 6
# За допомогою методу unique  перевірте. Які є унікальні жанри в стовпці genre  
unique_genres = data['genre'].unique()
print("Унікальні жанри в стовпці 'genre':")
print(unique_genres)

Унікальні жанри в стовпці 'genre':
['Non Fiction' 'Fiction']

In [10]:
# Завдання 7
# Визначте максимальну, мінімальну, медіанну ціну за допомогою методів  max, min, mean, median 
max_price = data['price'].max()
min_price = data['price'].min()
mean_price = data['price'].mean()
median_price = data['price'].median()

print("Максимальна ціна:", max_price)
print("Мінімальна ціна:", min_price)
print("Середня ціна:", mean_price)
print("Медіанна ціна:", median_price)

Максимальна ціна: 105
Мінімальна ціна: 0
Середня ціна: 13.1
Медіанна ціна: 11.0

In [26]:
# Завдання 8 
# Виконайте наступні завдання з пошуку і сортування даних 
# Який рейтинг у датасеті найвищий
max_rating = data['user_rating'].max()

print("Найвищий рейтинг:", max_rating)
print('\n')
# Скільки книг мають такий рейтинг?
count_books_with_rating_5 = data[data['user_rating'] == max_rating].shape[0]

print("Кількість книг з рейтингом 4.9:", count_books_with_rating_5)
print('\n')
# Яка книга має найбільше відгуків? 
index_of_book_with_max_reviews = data['reviews'].idxmax()

book_with_max_reviews = data.loc[index_of_book_with_max_reviews]

print("Книга з найбільшою кількістю відгуків:")
print(book_with_max_reviews['name'])
print('\n')
# З тих книг, що потрапили до Топ-50 у 2010 році, яка книга найдорожча ?
top_50_2010 = data[(data['year'] == 2010) & (data['user_rating'] <= 50)]

most_expensive = top_50_2010.loc[top_50_2010['price'].idxmax()]

print("Найдорожча книга серед тих, що потрапили до Топ-50 у 2010 році:")
print(most_expensive['name'])
print('\n')
# Скільки книг жанру Fiction потрапили до Топ-50 у 2012 році
top_50_2012 = data[(data['year'] == 2012) & (data['user_rating'] <= 50)]

fiction_books = top_50_2012[top_50_2012['genre'] == 'Fiction']

count_fiction_books_in_2012 = fiction_books.shape[0]

print("Кількість книг жанру Fiction у Топ-50 у 2012 році:", count_fiction_books_in_2012)
print('\n')
# Скільки книг з рейтингом 4.9 потрапило до рейтингу у 2010 та 2011 роках (використовуйте | або метод isin)? 
target_years = [2010, 2011]
target_rating = 4.9

filtered_books = data[((data['year'] == 2010) | (data['year'] == 2011)) & (data['user_rating'] == target_rating)]

count_books = filtered_books.shape[0]

print(f"Кількість книг з рейтингом 4.9 у 2010, 2011 роках: {count_books}")
print('\n')

Найвищий рейтинг: 4.9


Кількість книг з рейтингом 4.9: 52


Книга з найбільшою кількістю відгуків:
Where the Crawdads Sing


Найдорожча книга серед тих, що потрапили до Топ-50 у 2010 році:
Publication Manual of the American Psychological Association, 6th Edition


Кількість книг жанру Fiction у Топ-50 у 2012 році: 21


Кількість книг з рейтингом 4.9 у 2010, 2011 роках: 1

In [28]:
# Завдання 9
# Вивести максимальну і  мінімальну ціну для жанру Fiction I NonFiction (за допомогою методів  groupby та agg, для підрахунку мінімальних та максимальних значень використовуйте max та min)
result = data.groupby('genre').agg({'price': ['min', 'max']})

print(result)

            price
              min  max
genre
Fiction         0   82
Non Fiction     0  105